<?PHP
//command_baseの読み込み
    include_once "include/Util.php";

    include_once "./module/Report.inc";
//    include_once "./module/zip_match.inc";
//    include_once "./module/sendmail.inc";
//    include_once "./module/feed.inc";
//    include_once "./module/multimail.inc";
//    include_once "./module/Banner.inc";
//    include_once "./module/access.inc";
//    include_once "./module/clip.inc";
//    include_once "./module/s_condition.inc";
//    include_once "./module/sys_mail.inc";

    include_once "./module/time.inc";

    include_once "./module/category.inc";
    include_once "./module/news.inc";
    include_once "./module/adwares.inc";

//command
//    include_once "./module/command/xxxx.inc";

	include_once './module/access_trade.inc';
	include_once './module/sound_source.inc';
	include_once './module/vote.inc';
//	include_once './module/artist_enable.inc';  // アーティストを無効化する時は消す
	include_once './module/paid_point.inc';
